### ISSUE TITLE
alphagov/static fails to start when starting alphagov/publisher

### ISSUE THREAD

**Issue by gxrneyme** [alphagov/govuk-docker#237]
When trying to start `alphagov/publisher` using the command `govuk-docker-up`, the start-up process proceeds until recreating `alphagov/static`. It fails with the following output:

```
Recreating govuk-docker_static-app_1 ... error

ERROR: for govuk-docker_static-app_1  Cannot start service static-app: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"bin/rails\": stat bin/rails: no such file or directory": unknown

ERROR: for static-app  Cannot start service static-app: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"bin/rails\": stat bin/rails: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.
```

Any idea where to start with resolving this?

**Comment by connorgurney** [comment]
Hi Ben,

Many thanks, Ben—just tried to run it now. It succeeds down to setting up `alphagov/calendars` tries to connect to the E2E `alphagov/publishing-api` stack:

````
/Users/Connor/govuk/govuk-docker/exe/govuk-docker run calendars-setup bin/rake publishing_api:publish
Starting govuk-docker_postgres_1        ... done
Starting govuk-docker_rabbitmq_1        ... done
Starting govuk-docker_mongo_1           ... done
Starting govuk-docker_nginx-proxy-app_1 ... done
Starting govuk-docker_router-app_1       ... done
Starting govuk-docker_router-app-draft_1 ... done
Starting govuk-docker_router-api-app-draft_1 ... done
Starting govuk-docker_router-api-app_1       ... done
Starting govuk-docker_content-store-app-draft_1 ... done
Starting govuk-docker_content-store-app_1       ... done
Starting govuk-docker_publishing-api-worker_1   ... done
Starting govuk-docker_publishing-api-app-e2e_1  ... done
rake aborted!
GdsApi::HTTPInternalServerError: URL: http://publishing-api.dev.gov.uk/v2/content/58f79dbd-e57f-4ab2-ae96-96df5767d1b2
Response body:
Puma caught this error: File exists @ dir_s_mkdir - /govuk (Errno::EEXIST)
/home/build/.rbenv/versions/2.6.5/lib/ruby/2.6.0/fileutils.rb:239:in `mkdir'
/home/build/.rbenv/versions/2.6.5/lib/ruby/2.6.0/fileutils.rb:239:in `fu_mkdir'
/home/build/.rbenv/versions/2.6.5/lib/ruby/2.6.0/fileutils.rb:217:in `block (2 levels) in mkdir_p'
/home/build/.rbenv/versions/2.6.5/lib/ruby/2.6.0/fileutils.rb:215:in `reverse_each'
/home/build/.rbenv/versions/2.6.5/lib/ruby/2.6.0/fileutils.rb:215:in `block in mkdir_p'
/home/build/.rbenv/versions/2.6.5/lib/ruby/2.6.0/fileutils.rb:200:in `each'
/home/build/.rbenv/versions/2.6.5/lib/ruby/2.6.0/fileutils.rb:200:in `mkdir_p'
/home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/application.rb:597:in `generate_development_secret'
/home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/application.rb:430:in `secret_key_base'
/home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/application.rb:253:in `env_config'
/home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:706:in `build_request'
/home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/application.rb:608:in `build_request'
/home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:523:in `call'
/home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.2.1/lib/puma/configuration.rb:228:in `call'
/home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.2.1/lib/puma/server.rb:667:in `handle_request'
/home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.2.1/lib/puma/server.rb:470:in `process_client'
/home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.2.1/lib/puma/server.rb:328:in `block in run'
/home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.2.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread'

Request body:
{:title=>"UK bank holidays", :description=>"Find out when bank holidays are in England, Wales, Scotland and Northern Ireland - including past and future bank holidays", :base_path=>"/bank-holidays", :document_type=>"calendar", :schema_name=>"calendar", :publishing_app=>"calendars", :rendering_app=>"calendars", :locale=>"en", :details=>{:body=>""}, :public_updated_at=>"2019-10-30T15:59:54+00:00", :routes=>[{:type=>"prefix", :path=>"/bank-holidays"}], :update_type=>"minor"}
/govuk/calendars/app/services/calendar_publisher.rb:7:in `publish'
/govuk/calendars/lib/tasks/publishing_api.rake:6:in `block (3 levels) in <top (required)>'
/govuk/calendars/lib/tasks/publishing_api.rake:4:in `each'
/govuk/calendars/lib/tasks/publishing_api.rake:4:in `block (2 levels) in <top (required)>'

Caused by:
RestClient::InternalServerError: 500 Internal Server Error
/govuk/calendars/app/services/calendar_publisher.rb:7:in `publish'
/govuk/calendars/lib/tasks/publishing_api.rake:6:in `block (3 levels) in <top (required)>'
/govuk/calendars/lib/tasks/publishing_api.rake:4:in `each'
/govuk/calendars/lib/tasks/publishing_api.rake:4:in `block (2 levels) in <top (required)>'
Tasks: TOP => publishing_api:publish
(See full trace by running task with --trace)
make: *** [calendars] Error 1
````

Really quite confused as to why `~/govuk` existing is an issue... Any ideas?

**Comment by connorgurney** [comment]
Just as a heads-up, I've also tried to run `build calendars` and receive an identical error. However, the Publishing API URL works when accessed via a browser, so the 500 error seems weird.

**Comment by benthorner** [comment]
I'm afraid I can't reproduce the error you're having, although it's possible they're related. Can you post the output `govuk-docker run static-lite ls /govuk` and `govuk-docker run calendars-setup ls /govuk`?

**Comment by connorgurney** [comment]
Thanks, Ben. Per your request:

`govuk-docker run static-lite ls /govuk`:
````
docker-compose -f [...] run static-lite ls /govuk
calendars      govuk-content-schemas  publisher       router	  static
content-store  govuk-docker	      publishing-api  router-api
````

`govuk-docker run calendars-setup ls /govuk`
````
Starting govuk-docker_postgres_1        ... done
Starting govuk-docker_postgres_1 ... 
Starting govuk-docker_rabbitmq_1 ... done
Starting govuk-docker_redis_1           ... done
Starting govuk-docker_nginx-proxy-app_1 ... done
Starting govuk-docker_router-app-draft_1 ... done
Starting govuk-docker_router-app_1       ... done
Starting govuk-docker_router-api-app-draft_1 ... done
Starting govuk-docker_router-api-app_1       ... done
Starting govuk-docker_content-store-app-draft_1 ... done
Starting govuk-docker_content-store-app_1       ... done
Starting govuk-docker_publishing-api-worker_1   ... done
Starting govuk-docker_publishing-api-app-e2e_1  ... done
calendars      govuk-content-schemas  publisher       router	  static
content-store  govuk-docker	      publishing-api  router-api
````

**Comment by benthorner** [comment]
Hmmm...that seems OK. Can you try a few more things:

```
govuk-docker run static-lite ls
govuk-docker run publishing-api-e2e ls /govuk
govuk-docker run publishing-api-e2e ls
```

It might also be worth retrying your original command to start publisher, as the build issue you're getting might be completely unrelated and less valuable to fix.

**Comment by connorgurney** [comment]
`static-lite` returns nothing, while both `publishing-api-e2e` commands return `ERROR: No such service: publishing-api-e2e`. The Publishing API has been cloned and seems to all be in order within `~/govuk`.

**Comment by connorgurney** [comment]
Recloned everything and tried again—`make publisher` works fine, but `govuk-docker-up` outputs:

`docker-compose -f [...] up publisher-app
govuk-docker_postgres_1 is up-to-date
govuk-docker_nginx-proxy-app_1 is up-to-date
govuk-docker_redis_1 is up-to-date
govuk-docker_mongo_1 is up-to-date
Starting govuk-docker_link-checker-api-worker_1 ... 
Starting govuk-docker_static-app_1              ... 
govuk-docker_publishing-api-app_1 is up-to-date
Starting govuk-docker_link-checker-api-worker_1 ... done
Starting govuk-docker_static-app_1              ... error
Starting govuk-docker_content-store-app_1       ... done
Starting govuk-docker_link-checker-api-app_1    ... 

ERROR: for govuk-docker_static-app_1  Cannot start service static-app: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"bin/rails\": stat bin/rails: no sStarting govuk-docker_link-checker-api-app_1    ... done

ERROR: for static-app  Cannot start service static-app: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"bin/rails\": stat bin/rails: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.`

I've tried running `govuk-docker run static-lite ls /govuk` which returns the same as `ls ~/govuk`, while `govuk-docker run static-lite ls` returns nothing.

**Comment by benthorner** [comment]
OK. I'm glad `make publisher` works OK. I was really struggling to work out what was going on there, but it seems unrelated to the `static` issue, for which I think I know the cause.

I think some previous build of `static` failed on your machine. Normally running `make` would fix the issue, but a few small bugs in the repo mean that hasn't happened.

I'll look at raising PRs to fix the bugs, but in the meantime I think you can make progress by doing `rm -r ~/govuk/static` and then `make static` in `govuk-docker`.

**Comment by connorgurney** [comment]
`make static` seems to now run fine, but I'm now confronted with an error about MongoDB which I suspect is unrelated to this. 

````
Starting govuk-docker_mongo_1 ... done
Traceback (most recent call last):
	21: from bin/rails:4:in `<main>'
	20: from bin/rails:4:in `require'
	19: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
	18: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
	17: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
	16: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	15: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	14: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	13: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:41:in `perform'
	12: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:41:in `eval'
	11: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
	10: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongoid-6.2.1/lib/mongoid/findable.rb:148:in `first'
	 9: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongoid-6.2.1/lib/mongoid/contextual.rb:20:in `first'
	 8: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongoid-6.2.1/lib/mongoid/contextual/mongo.rb:255:in `first'
	 7: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongoid-6.2.1/lib/mongoid/contextual/mongo.rb:522:in `try_cache'
	 6: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongoid-6.2.1/lib/mongoid/contextual/mongo.rb:257:in `block in first'
	 5: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongoid-6.2.1/lib/mongoid/contextual/mongo.rb:257:in `first'
	 4: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongoid-6.2.1/lib/mongoid/query_cache.rb:222:in `each'
	 3: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongo-2.4.3/lib/mongo/collection/view/iterable.rb:39:in `each'
	 2: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongo-2.4.3/lib/mongo/retryable.rb:43:in `read_with_retry'
	 1: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongo-2.4.3/lib/mongo/collection/view/iterable.rb:40:in `block in each'
/home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongo-2.4.3/lib/mongo/server_selector/selectable.rb:115:in `select_server': No server is available matching preference: #<Mongo::ServerSelector::Primary:0x46936051702920 tag_sets=[] max_staleness=nil> using server_selection_timeout=30 and local_threshold=0.015 (Mongo::Error::NoServerAvailable)
````

Tried recloning `alphagov/publisher` and restarting Docker with no luck. Looks like Mongo is failing to start within the container, but unsure why and not sure how to debug further. Any ideas?

**Comment by benthorner** [comment]
Glad to hear static is better! Could you clarify what command you're running when you get this error?

**Comment by gurneyconnor** [comment]
Sorry, thought I'd mentioned it in my comment—I'm running `make publisher` following `make static`.

**Comment by benthorner** [comment]
Thanks @gurneyconnor. `make` runs quite a few things. Can you give a bit more of the terminal output before the error?

**Comment by gurneyconnor** [comment]
Sure thing, @benthorner — I think this explains in more detail:

````
/Users/Connor/govuk/govuk-docker/exe/govuk-docker run content-store-lite bin/rake db:create
docker-compose -f [...] run content-store-lite bin/rake db:create
Starting govuk-docker_mongo_1 ... done
/Users/Connor/govuk/govuk-docker/exe/govuk-docker run content-store-lite bin/rails runner 'User.first || User.create'
docker-compose -f [...] run content-store-lite bin/rails runner User.first || User.create
Starting govuk-docker_mongo_1 ... done
Traceback (most recent call last):
	21: from bin/rails:4:in `<main>'
	20: from bin/rails:4:in `require'
	19: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
	18: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
	17: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
	16: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	15: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	14: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	13: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:41:in `perform'
	12: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:41:in `eval'
	11: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
	10: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongoid-6.2.1/lib/mongoid/findable.rb:148:in `first'
	 9: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongoid-6.2.1/lib/mongoid/contextual.rb:20:in `first'
	 8: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongoid-6.2.1/lib/mongoid/contextual/mongo.rb:255:in `first'
	 7: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongoid-6.2.1/lib/mongoid/contextual/mongo.rb:522:in `try_cache'
	 6: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongoid-6.2.1/lib/mongoid/contextual/mongo.rb:257:in `block in first'
	 5: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongoid-6.2.1/lib/mongoid/contextual/mongo.rb:257:in `first'
	 4: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongoid-6.2.1/lib/mongoid/query_cache.rb:222:in `each'
	 3: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongo-2.4.3/lib/mongo/collection/view/iterable.rb:39:in `each'
	 2: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongo-2.4.3/lib/mongo/retryable.rb:43:in `read_with_retry'
	 1: from /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongo-2.4.3/lib/mongo/collection/view/iterable.rb:40:in `block in each'
/home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mongo-2.4.3/lib/mongo/server_selector/selectable.rb:115:in `select_server': No server is available matching preference: #<Mongo::ServerSelector::Primary:0x47425298430440 tag_sets=[] max_staleness=nil> using server_selection_timeout=30 and local_threshold=0.015 (Mongo::Error::NoServerAvailable)
make: *** [content-store] Error 1
````

**Comment by benthorner** [comment]
This looks like the content-store container is having trouble communicating with the mongo container. One reason for this could be the mongo container isn't starting properly: can you check its status with `govuk-docker ps` and `govuk-docker logs mongo` after running this command? 

Another reason could be that you're using an outdated or modified version of the content-store repo - I'm not sure if you have had content-store cloned previously. Can you check that your local content-store repo is up-to-date with respect to the origin?

**Comment by gxrneyme** [comment]
Hi Ben,

Sorry for the delay in responding to you—been away! I reset Docker to factory settings and all seems to work well.

However, if anyone comes across this in the future, it seemed to be an issue with files in `/data/db` of the MongoDB container being corrupted—presumably through force-closing the container. [Documentation on how to repair the files from MongoDB.org](http://www.mongodb.org/dochub/core/repair) might be helpful.

Thanks for all your help—you've been a star!

**Comment by benthorner** [comment]
No problem @gxrneyme! This issue identified a few things to fix, which will benefit all the developers on GOV.UK 🎉
