### ISSUE TITLE
Foreign key constraint failure in collections-publisher-lite db:setup

### ISSUE THREAD

**Issue by aldavidson** [alphagov/govuk-docker#491]
On a first-ever run of `make collections-publisher`, I get this error:

```
docker-compose -f [...] run collections-publisher-lite bin/rake db:setup
Creating govuk-docker_collections-publisher-lite_run ... done
Created database 'collections_publisher_development'
Created database 'collections_publisher_test'
/home/al/govuk/govuk-docker/exe/govuk-docker run collections-publisher-lite env RAILS_ENV=test bin/rake db:setup
docker-compose -f [...] run collections-publisher-lite env RAILS_ENV=test bin/rake db:setup
Creating govuk-docker_collections-publisher-lite_run ... done
Database 'collections_publisher_test' already exists
rake aborted!
ActiveRecord::InvalidForeignKey: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails
/govuk/collections-publisher/db/schema.rb:25:in `block in <top (required)>'
/govuk/collections-publisher/db/schema.rb:13:in `<top (required)>'
Caused by:
Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails
/govuk/collections-publisher/db/schema.rb:25:in `block in <top (required)>'
/govuk/collections-publisher/db/schema.rb:13:in `<top (required)>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```

I've worked around it using @kevindew 's suggestion in [this Slack thread](https://gds.slack.com/archives/CAB4Q3QBW/p1621953048057800?thread_ts=1621951685.053200&cid=CAB4Q3QBW) -

1. run `govuk-docker run collections-publisher-lite bin/rails db:drop`
2. comment out the second `db:setup` invocation for the test environment on [line 3 of the collections-publisher Makefile](https://github.com/alphagov/govuk-docker/blob/2fe4ee96cfd4fdae9a042727cefb79b85889b8f1/projects/collections-publisher/Makefile#L3)
3. re-run `make collections-publisher`

- but it would be good to fix the issue for the next new starter

**Comment by kevindew** [comment]
Thanks for raising this @aldavidson and welcome to GOV.UK 🎉 

For further context, there seems to be a couple of issues at play. At the root of this there is a problem where there is an expectation that rake db:setup is consistently idempotent - whereas it only seems to be partially (it'll break on db:schema:load for MySQL) - @benthorner any thoughts on if we should reconsider returning to the conditionals of https://github.com/alphagov/govuk-docker/commit/1ec59d4543c30103a7b36129289e0135c77a61ca ?

Then there's an issue that this actually fails on a first execution due to Collections Publisher being a Rails 6.0 app and not benefiting from the 6.1 fix of https://github.com/alphagov/govuk-docker/blob/2fe4ee96cfd4fdae9a042727cefb79b85889b8f1/projects/collections-publisher/Makefile#L3 - this seems a minor concern since it wouldn't be a problem if idempotency was resolved and the app will (hopefully) be upgraded to 6.1 in the coming weeks.

**Comment by benthorner** [comment]
Thanks for investigating a bit @kevindew ⭐. I've had a look and agree MySQL does have an annoyingly different behaviour. Since we have so few apps using MySQL, it's likely I didn't test them in 1ec59d4. 

All of our MySQL apps still seem to be on Rails 6.0. I tried a quick upgrade of Collections Publisher, and the initial setup issue was indeed resolved by the behaviour change, since the test DB isn't setup with the dev one.

I can think of a few options to get it working again:

1. Revert 1ec59d4. Tempting, but not ideal, as it confuses the purpose again.
2. Remove the second `db:setup` until each app upgrades to 6.1 (maybe just comment it out).
3. Catch the error and warn about it (optionally remove the catch after upgrading).
4. Switch to `db:drop db:setup`, to prevent the error (could be unexpected).
5. ~~Switch to `db:create db:migrate db:seed`~~ (doesn't work as old migration files are broken).

I dislike the second option, as while people shouldn't be constantly using `make bootstrap`, it's confusing if you do run it again and it errors: it's unclear if the app is broken, GOV.UK Docker is broken, or that you can't run it twice.

I'm tempted to go with option 3:

- We're not hiding the error, or doing something surprising.
- The error is a good prompt you shouldn't rerun `make bootstrap`.
- It'll work before and after the upgrade to 6.1.

What do you think?

**Comment by kevindew** [comment]
Thanks for taking a look Ben.

> I can think of a few options to get it working again:
> 
> 1. Revert [1ec59d4](https://github.com/alphagov/govuk-docker/commit/1ec59d4543c30103a7b36129289e0135c77a61ca). Tempting, but not ideal, as it confuses the purpose again.
> 2. Remove the second `db:setup` until each app upgrades to 6.1 (maybe just comment it out).
> 3. Catch the error and warn about it (optionally remove the catch after upgrading).
> 4. Switch to `db:drop db:setup`, to prevent the error (could be unexpected).
> 5. ~Switch to `db:create db:migrate db:seed`~ (doesn't work as old migration files are broken).

I agree with your reasonings for not wanting option 2 or 4. 👍 

I'm not quite convinced by a warning though as this isn't necessarily a mistake (even if all apps are 6.1) given make has dependencies you could easily re-run make on an all that is already run without having a set-up step.

I find myself leaning more towards option 1, however I believe there is a short hand Rails task we can use instead,  [`db:prepare`](https://github.com/rails/rails/blob/fdce2a22347c96d34245bcbd9d14d6d02366c44f/activerecord/lib/active_record/railties/databases.rake#L356-L357) which does setup for no db or migrate if one exists, it arrived in Rails 6.

**Comment by benthorner** [comment]
> I'm not quite convinced by a warning though as this isn't necessarily a mistake

Yeah, there are several reasons someone might re-run the Makefile for an app. "warning" was a bit vague. It would just be some message to try and explain the error that preceded it, so the user wouldn't be alarmed.

However...

> I believe there is a short hand Rails task we can use instead, db:prepare

That's a much a better outcome! Let's do that: https://github.com/alphagov/govuk-docker/pull/494
